# Toolchain-File für Linux Host mit Clang und Buildroot-Sysroot (ARMv7)
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)

IF(NOT DEFINED ENV{{SYSROOT}})
  MESSAGE(FATAL_ERROR "SYSROOT environment variable is not set")
ENDIF()

SET(CMAKE_SYSROOT $ENV{{SYSROOT}})
SET(CMAKE_FIND_ROOT_PATH $ENV{{SYSROOT}})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(CMAKE_C_COMPILER_TARGET armv7a-linux-gnueabihf)
SET(CMAKE_CXX_COMPILER_TARGET armv7a-linux-gnueabihf)
